### PR TITLE
Merging JWPL code 

### PR DESCRIPTION
**Pull request by dav009**
- Copied [JWPL's code](https://github.com/idio/jwpl) here. `api`, `parser` and `util` packages.  (including tests)
- Sacked off JWPL's dependency from the pom
- Sacked off the jar from the project's maven repo

Why are we doing this:

- JWPL is not longer maintained. Everytime we make a change there, we have to submit a new jar to this repo.

- ~~An alternative to doing this is mantaining JWPL's code in its own repo and use https://jitpack.io/ adding that jar as a dependency of this repo. (after doing this PR, this option does not look so bad)~~

- To do: get this as an sbt project? I thought this PR was already long , bringing more changes could get confusing among the 1000added files.

### CODE REVIEW

**Comment by keynmol** [comment]
# Haha. No.

**Comment by dav009** [comment]
Travis outage : https://www.traviscistatus.com/
screen shot 2015-08-25 at 11 43 21

**Comment by dav009** [comment]
@keynmol  label label ;)?

**Pull request merged**
